# 测试
debug: true

server:
  servlet:
    session:
      persistent: false
      cookie:
        http-only: true
      timeout: 60m
  error:
    path: /error
  port: 10086
  compression:
    enabled: true


logging:
  level:
    org:
#      thymeleaf: TRACE
#      springframework: TRACE
#      security: TRACE
#      hc.client5: TRACE
#      scheduling.concurrent.ThreadPoolTaskExecutor: TRACE


spring:
  devtools:
    restart:
      enabled: false



# 所有下载文件的存放路径
timepill.fileBasePath: C:/timepill-backup/