name: Build GraalVM Native Image

on:
  push:
    tags:
      - 'v*.*.*'  # 只有当推送 tag 时才会触发这个工作流
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]  # 定义需要运行的操作系统
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # 你也可以选择其他的 JDK 发行版

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'  # 请根据需要选择 GraalVM 的版本
          java-version: '17'
          components: native-image

      - name: Build with Maven
        run: mvn -Pnative native:compile -DskipTests

      - name: Archive native image
        if: runner.os == 'macOS'
        run: mv target/timepill-backup-17 timepill-backup-17-macos
      - name: Archive native image
        if: runner.os == 'Windows'
        run: mv target/timepill-backup-17.exe timepill-backup-17-windows.exe

      - name: Upload native image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: native-image-${{ matrix.os }}
          path: ${{ runner.os == 'macOS' && 'timepill-backup-17-macos' || 'timepill-backup-17-windows.exe' }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: native-image-macos
          path: ./dist
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: native-image-windows
          path: ./dist

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            dist/timepill-backup-17-macos
            dist/timepill-backup-17-windows.exe
