name: Build GraalVM Native Image

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
     - name: Check iexpress.exe availability (Windows)
       if: runner.os == 'Windows'
       shell: cmd
       run: |
          where.exe iexpress.exe
          if %errorlevel% neq 0 (
            echo "iexpress.exe not found. Please make sure it's installed and available in the system PATH."
            exit 1
          )
