name: Build GraalVM Native Image

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          components: native-image

      - name: Build with Maven
        run: mvn -Pnative native:compile -DskipTests
        env:
          MAVEN_OPTS: '-Dfile.encoding=UTF-8'

      - name: Create self-extracting EXE using IEXPRESS (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          @echo off
          echo @echo off > run_utf8.bat
          echo chcp 65001 ^>nul >> run_utf8.bat
          echo start "" "aaa.EXE" %%* >> run_utf8.bat
          
          REM Create IEXPRESS SED file
          (
            echo [Version]
            echo Class=IEXPRESS
            echo SEDVersion=3
            echo [Options]
            echo PackagePurpose=InstallApp
            echo ShowInstallProgramWindow=1
            echo HideExtractAnimation=1
            echo UseLongFileName=1
            echo InsideCompressed=0
            echo CAB_FixedSize=0
            echo CAB_ResvCodeSigning=0
            echo RebootMode=N
            echo InstallPrompt=
            echo DisplayLicense=
            echo FinishMessage=
            echo TargetName=timepill-backup-17-windows.exe
            echo FriendlyName=timepill-backup
            echo AppLaunched=cmd.exe /c "run_utf8.bat"
            echo PostInstallCmd=<None>
            echo AdminQuietInstCmd=
            echo UserQuietInstCmd=
            echo FILE0="aaa.EXE"
            echo FILE1="run_utf8.bat"
            echo [SourceFiles]
            echo SourceFiles0=.
            echo [SourceFiles0]
            echo %%FILE0%%=
            echo %%FILE1%%=
          ) > config.sed

          REM Generate the self-extracting EXE using IEXPRESS
          iexpress.exe /N /Q /M config.sed

          REM Check if the file is created
          if exist "timepill-backup-17-windows.exe" (
            echo Self-extracting EXE created successfully.
          ) else (
            echo Failed to create self-extracting EXE.
            exit /b 1
          )

      - name: Rename native image (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir -p ./timepill-backup-17-macos
          mv target/native/timepill-backup-17 ./timepill-backup-17-macos/timepill-backup-17

      - name: Upload native image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-image-${{ matrix.os }}
          path: ${{ runner.os == 'macOS' && './timepill-backup-17-macos/timepill-backup-17' || './timepill-backup-17-windows.exe' }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: List contents of the workspace
        run: ls -R

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: native-image-macos-latest
          path: ./dist

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: native-image-windows-latest
          path: ./dist

      - name: List target directory
        run: ls -R ./dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: binaries-${{ github.run_id }}
          release_name: release-${{ github.run_id }}
          draft: false
          prerelease: false

      - name: Upload macOS binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/timepill-backup-17
          asset_name: timepill-backup-17-macOS
          asset_content_type: application/octet-stream

      - name: Upload Windows binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/timepill-backup-17-windows.exe
          asset_name: timepill-backup-17-windows.exe
          asset_content_type: application/octet-stream
